# Generated by Django 5.1.4 on 2026-06-07 17:00

import apps.crm.models
import django.db.models.deletion
import django_fsm
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('naturaleza', models.CharField(choices=[('SVC_DIG', 'Servicio Digital/Intangible'), ('PROD_FIS', 'Producto Físico/Manufactura')], max_length=10)),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidad'), ('MIL', 'Millar'), ('M2', 'Metro cuadrado'), ('ML', 'Metro lineal'), ('HR', 'Hora'), ('MES', 'Mes'), ('GLOB', 'Global/Lote')], default='UND', max_length=10)),
                ('tarifa_iva', models.CharField(choices=[('15.00', 'IVA 15%'), ('0.00', 'IVA 0% / Exento'), ('5.00', 'IVA 5% (bienes especiales)')], default='15.00', max_length=5)),
                ('precio_base_unitario', models.DecimalField(decimal_places=4, help_text='Precio de lista sin IVA. Puede sobreescribirse en el pedido.', max_digits=12)),
                ('requiere_dimensiones', models.BooleanField(default=False, help_text='Si True, el precio = precio_base * ancho_m * alto_m.')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ítem de Catálogo',
                'verbose_name_plural': 'Catálogo de Ítems',
                'ordering': ['naturaleza', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ING', 'Ingreso'), ('EGR', 'Egreso')], max_length=3)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría Financiera',
                'verbose_name_plural': 'Categorías Financieras',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidad'), ('MIL', 'Millar'), ('M2', 'Metro cuadrado'), ('ML', 'Metro lineal'), ('HR', 'Hora'), ('MES', 'Mes'), ('GLOB', 'Global/Lote')], max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Alerta cuando el stock baje de este nivel.', max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=4, help_text='Costo de compra por unidad, sin IVA.', max_digits=12)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('CED', 'Cédula'), ('RUC', 'RUC'), ('PAS', 'Pasaporte')], default='CED', max_length=3)),
                ('numero_identificacion', models.CharField(help_text='Cédula (10 dígitos) o RUC (13 dígitos).', max_length=13, unique=True, validators=[apps.crm.models.validar_identificacion_ecuador])),
                ('razon_social', models.CharField(help_text='Nombre completo o razón social.', max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254)),
                ('telefono_principal', models.CharField(blank=True, max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('aplica_retencion_fuente', models.BooleanField(default=False, help_text='Marcar si este cliente es agente de retención.')),
                ('porcentaje_retencion_fuente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ej: 1.00 para 1%, 2.00 para 2%. Solo si aplica retención.', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(help_text='Formato sugerido: ORD-YYYY-NNNNN. Generado automáticamente.', max_length=20, unique=True)),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('CRITICA', 'Crítica / Express')], default='NORMAL', max_length=10)),
                ('descripcion_general', models.TextField(blank=True)),
                ('fecha_compromiso', models.DateField(blank=True, help_text='Fecha prometida de entrega.', null=True)),
                ('estado', django_fsm.FSMField(choices=[('COTIZADO', 'Cotizado'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('EN_DISENIO', 'En Diseño'), ('EN_PRODUCCION', 'En Producción'), ('LISTO_ENTREGA', 'Listo para Entrega'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='COTIZADO', max_length=50, protected=True)),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_orden', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='crm.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='crm.orden')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['timestamp'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='ConsumoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('costo_unitario_momento', models.DecimalField(decimal_places=4, help_text='Costo al momento del consumo (snapshot histórico).', max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.materiaprima')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='crm.orden')),
            ],
            options={
                'verbose_name': 'Consumo de Materia Prima',
                'verbose_name_plural': 'Consumos de Materia Prima',
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_personalizada', models.CharField(blank=True, help_text='Si difiere del catálogo, describe el trabajo específico.', max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Unidades, metros², millares, etc.', max_digits=12)),
                ('ancho_m', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('alto_m', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('precio_unitario_neto', models.DecimalField(decimal_places=4, help_text='Precio unitario SIN IVA. Copia el precio_base del catálogo pero es editable.', max_digits=12)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento en porcentaje sobre el precio neto. Ej: 10.00 para 10%.', max_digits=5)),
                ('tarifa_iva', models.CharField(choices=[('15.00', 'IVA 15%'), ('0.00', 'IVA 0% / Exento'), ('5.00', 'IVA 5% (bienes especiales)')], help_text='Heredada del catálogo; modificable por ítem.', max_length=5)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('orden_linea', models.PositiveSmallIntegerField(default=1, help_text='Orden visual en la cotización.')),
                ('notas', models.TextField(blank=True)),
                ('catalogo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='crm.catalogoitem')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.orden')),
            ],
            options={
                'verbose_name': 'Línea de Orden',
                'verbose_name_plural': 'Líneas de Orden',
                'ordering': ['orden', 'orden_linea'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(help_text='Número de factura, recibo, egreso. Ej: FAC-2024-001.', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('ING', 'Ingreso'), ('EGR', 'Egreso')], max_length=3)),
                ('descripcion', models.TextField()),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porción del monto_neto gravada con IVA ≠ 0.', max_digits=14)),
                ('tarifa_iva_aplicada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tasa real aplicada. Ej: 15.00 o 0.00.', max_digits=5)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='= base_iva × tarifa_iva_aplicada / 100. Calculado automáticamente.', max_digits=14)),
                ('retencion_fuente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención en la fuente aplicada por el cliente (si es ag. retención).', max_digits=14)),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención de IVA (30%, 70%, 100% del IVA según tipo de cliente).', max_digits=14)),
                ('monto_flujo_caja', models.DecimalField(decimal_places=2, editable=False, help_text='= monto_neto + monto_iva − ret_fuente − ret_iva.', max_digits=14)),
                ('metodo_pago', models.CharField(choices=[('EFEC', 'Efectivo'), ('TRANSF', 'Transferencia Bancaria'), ('T_DEB', 'Tarjeta de Débito'), ('T_CRED', 'Tarjeta de Crédito'), ('CHQ', 'Cheque'), ('OTRO', 'Otro')], max_length=10)),
                ('fecha_emision', models.DateField(help_text='Fecha del documento fiscal.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('anulada', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.categoriafinanciera')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='crm.cliente')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='crm.orden')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('transaccion_origen', models.ForeignKey(blank=True, help_text='Si esta transacción es un contra-asiento, apunta a la original.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contra_asientos', to='crm.transaccion')),
            ],
            options={
                'verbose_name': 'Transacción Financiera',
                'verbose_name_plural': 'Transacciones Financieras',
                'ordering': ['-fecha_emision', '-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['numero_identificacion'], name='crm_cliente_numero__b99773_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['estado'], name='crm_orden_estado_3ecb28_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['cliente', 'estado'], name='crm_orden_cliente_8c342c_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['fecha_compromiso'], name='crm_orden_fecha_c_c01511_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordenitem',
            constraint=models.UniqueConstraint(fields=('orden', 'orden_linea'), name='uq_orden_linea_numero'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo', 'fecha_emision'], name='crm_transac_tipo_2bd6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['anulada', 'tipo'], name='crm_transac_anulada_4134f2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['orden'], name='crm_transac_orden_i_c29c80_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.UniqueConstraint(fields=('referencia',), name='uq_transaccion_referencia'),
        ),
    ]
