# Generated by Django 5.1.4 on 2026-06-13 00:52

import apps.crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_transaccion_registrado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_identificacion',
            field=models.CharField(error_messages={'unique': 'Ya existe un cliente registrado con este número de identificación.'}, help_text='Cédula (10 dígitos) o RUC (13 dígitos).', max_length=13, unique=True, validators=[apps.crm.models.validar_identificacion_ecuador]),
        ),
    ]
